language: python

services:
  - docker

script:
  - make

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
   docker tag logspout-unomaly:1.${TRAVIS_BUILD_NUMBER};
   docker push unomaly/logspout-unomaly:1.${TRAVIS_BUILD_NUMBER};
   fi
